# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:  # 允许手动触发
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set Config
        run: pnpm config set strict-ssl false

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Configure .npmrc
        run: |
          echo "@pandapro-project:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GT_TOKEN }}" >> .npmrc

      - name: Npm Login
        run: npm login

      - name: Npm Publish
        run: npm publish
